### ISSUE TITLE
NoSuchElementException on Scanner from user imput

### ISSUE THREAD

**Issue by computing-lex** [tanzdoesthings/AUTODUNGEON#2]
`Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.Scanner.throwFor(Scanner.java:941)
        at java.base/java.util.Scanner.next(Scanner.java:1598)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2263)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2217)
        at AUTODUNGEON.entities.Player.move(Player.java:36)
        at AUTODUNGEON.DungeonController.movePlayer(DungeonController.java:31)
        at AUTODUNGEON.DungeonController.update(DungeonController.java:20)
        at Main.main(Main.java:7)`

**Comment by computing-lex** [comment]
No longer occurs
